### ISSUE TITLE
Melonloader does not work in the latest versions

### ISSUE THREAD

**Issue by MrEoZ-MRZ** [Cr4nkSt4r/phasmophobia-melon-mod#11]
I saw this project keep updating but melonloader stopped being compatible with phasmophobia, how can it be used now?

**Comment by MrEoZ-MRZ** [comment]
[13:09:55.345] [MelonLoader] Cleaning C:\Program Files (x86)\Steam\steamapps\common\Phasmophobia\MelonLoader\Dependencies\AssemblyGenerator\UnityDependencies
[13:09:55.345] [MelonLoader] Downloading https://github.com/HerpDerpinstine/MelonLoader/raw/master/BaseLibs/UnityDependencies/2019.4.28.zip to C:\Users\Nazareno Busi\AppData\Local\Temp\tmpA51A.tmp
Unable to read VR Path Registry from C:\Users\Nazareno Busi\AppData\Local\openvr\openvrpaths.vrpath
Unable to read VR Path Registry from C:\Users\Nazareno Busi\AppData\Local\openvr\openvrpaths.vrpath
Unable to read VR Path Registry from C:\Users\Nazareno Busi\AppData\Local\openvr\openvrpaths.vrpath

**Comment by MrEoZ-MRZ** [comment]
and generate an automatic closing of the game

**Comment by Cr4nkSt4r** [comment]
I'm using **v0.4.3 Open-Beta**
The download stuff is something they added to prevent it from working with phas.
They are reading the json from [ML api](https://api.melonloader.com/api/v1/game/phasmophobia)
and just manipulating the return values in a way, which MelonLoader does not like.
Can be easily circumvented.

As second measurement, they are checking, if the game is phasmophobia, before they even get to the download and the Bootstrapper will just close itself, so MelonLoader does not even gets loaded.


Just download their latest sourcecode and make changes to the Bootstrap project and the Il2CppAssemblyGenerator one.

[Bootstrap](https://prnt.sc/1s3f216)
[Il2CppAssemblyGenerator](https://prnt.sc/1s3f4fo)

Il2CppAssemblyGenerator can be circumvented in many ways, I personally choosed another simpler way, but this will work too.

**Comment by MrEoZ-MRZ** [comment]
I made those modifications in MelonLoader and it still doesn't work, is it possible that you leave your MelonLoader in this repository to use together with Phasmophobia?

**Comment by AshleyHolton** [comment]
The issue has been closed. Melonloader changes will not be put here, however, it has been mentioned on the forum already how to get it to work several times.

**Comment by Cr4nkSt4r** [comment]
For other people, the instructions where pretty clear.
But MelonLoader source or modified files, have nothing to do with this mod, so they won't be included, sorry.

**Comment by steeven00** [comment]
when i look at the change of the bootstrap i dont see any change on the code, also did all the change and phasmo wont launch, it is not working for me

**Comment by MrEoZ-MRZ** [comment]
> when i look at the change of the bootstrap i dont see any change on the code, also did all the change and phasmo wont launch, it is not working for me

me too xD

**Comment by AshleyHolton** [comment]
It's kind of a required thing to hook onto existing game functionality. Perhaps read the instructions and previous questions/answers.

**Comment by Cr4nkSt4r** [comment]
> > should prob. gonna check version control and how changed things will be shown.
> > Every line with a green bg have changed code inside, so double check to your local code.
> > Other people did it too, with the same
> 
> ok, maybe try edit your version to work without melonloader

It's a MelonLoader mod, there is no intention to run without MelonLoader, would make zero sence.
You could try, to make a own menu and share with the community as a open source project.
This project is open source, make changes to plain code and publish them would work too.

I have closed source projects, including Phasmophobia, but that's nothing to share with the public in general.
I was thinking about releasing some independent c++ Phasmophobia project, but this repo never got any big contributions from the community, so the other menu wouldn't as well.
Most people just use it as a base and add their own stuff to it, but when never sharing stuff back to the community, there is no need to have anything new shared to the same people.

The same people are often to lazy to read existing issues and create new ones instead.
So for the same people, stuff got more casual related to building this project.
I thought, opening the issues for the mod, would cause some real issue reports, to maybe get some stuff fixed, but I was wrong.

But I still keep trying to make crucial functionality updates in my free time, when the game gets a big update with new stuff, even with this project being discontinued.
So please have mercy, that I won't make this mod a standalone version for this game.
