### ISSUE TITLE
cant compile

### ISSUE THREAD

**Issue by Rademenes16** [Cr4nkSt4r/phasmophobia-melon-mod#12]
im getting 80+ errors each time i want to compile. I DID change the directory in .csproj to phasmo root folder and also tried \Phasmophobia\MelonLoader\Managed path, set the release x64 and I have melon installed properly. Nothing worked so far. Update your readme or your code.

**Comment by Cr4nkSt4r** [comment]
Then you just can't follow the simple text in the readme.
I don't have to update the source nor the readme, everything is just fine.
