### ISSUE TITLE
MelonMod Reference(VC 2019)

### ISSUE THREAD

**Issue by turaki0423** [Cr4nkSt4r/phasmophobia-melon-mod#14]
I was using MelonMod.dll (v0.2.7.4) and it can't be used in the project, but v0.4.3.0 is usable.
v0.4.3.0 melonloader is making Phas crashing but v0.2.7.4 is working.
I chose v0.4.3.0 as the reference and compiled(success).
did I make something wrong?

**Comment by Cr4nkSt4r** [comment]
**Dublicate issue:** #11
