### ISSUE TITLE
door problem

### ISSUE THREAD

**Issue by osmancitci** [Cr4nkSt4r/phasmophobia-melon-mod#15]
When we enter the hunt mode, the doors close, except for me, he passes through those doors, but it always seems closed to me. I'm staying inside the house it only seems to me there is a ghost problem needs to be fixed

**Comment by Cr4nkSt4r** [comment]
This project is discontinued for a while now and only receives updates for crucial stuff like the new ghsots and evidence changes.
Other Features won't receive any update.
If anyone wants to contribute fixes or new functions, they can make a merge request.

But the ghost always went through doors.
If the doors do not sync prop., 1. be host and 2. close the doors beforehand, the lock state should still sync.
