### ISSUE TITLE
Could not build due to can not run the game with Bypass.

### ISSUE THREAD

**Issue by Naexen** [Cr4nkSt4r/phasmophobia-melon-mod#17]
Hello. I tried to download vscode and ran the PhasBypass.sln file for bypass and found the PhasBypass.dll file in the PhasBypass\x64\Debug directory. Trying to run the game by loading it into the common\Phasmophobia\Plugins directory failed. But I saw in the build tutorial
"ML will download stuff to handle the IL2CPP from Phasmophobia" I don't know how to access Next step.
What should I do?

**Comment by Cr4nkSt4r** [comment]
I can't help if the How to build section wasn't followed.

**Comment by Naexen** [comment]
If you are talking about the second step not opening the game with the mod. I have tried very many times and it does not start.

**Comment by Cr4nkSt4r** [comment]
Why do you open a new issue then, instead of looking through the solved ones?
Everything was already covered:
https://github.com/Cr4nkSt4r/phasmophobia-melon-mod/issues/11

**Comment by Cr4nkSt4r** [comment]
Is it working now?
