### ISSUE TITLE
Light Flicker

### ISSUE THREAD

**Issue by Glatrix** [Cr4nkSt4r/phasmophobia-melon-mod#6]
When I try to use all "Blinking lights", They blink for a second and then they all just turn on. Maybe a fix for this could be Blinking lights on/off separate buttons and put light blinking through a loop? 

besides that... good job! Looking forward to more features

**Comment by Cr4nkSt4r** [comment]
I've already tried that one time and it didn't worked.
I gave it another try and I got it tp work.
Will be added in the next update.

**Comment by Glatrix** [comment]
Cant Wait, Keep up the good work!

**Comment by Cr4nkSt4r** [comment]
**Added feature with commit:** 89f67d464b1fdf841d27f58e8432165465e04a80
